apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrimmage-telegram-event-integration
  namespace: default
  labels:
    app: scrimmage-telegram-event-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrimmage-telegram-event-integration
  template:
    metadata:
      labels:
        app: scrimmage-telegram-event-integration
    spec:
      containers:
        - name: scrimmage-telegram-event-integration
          image: public.ecr.aws/u8g2k1e9/scrimmage-telegram-event-integration:1.1.3
          env:
            - name: TELEGRAM_TOKEN
              value: ""
            - name: SCRIMMAGE_API_SERVER_ENDPOINT
              value: ""
            - name: SCRIMMAGE_PRIVATE_KEY
              value: ""
            - name: SCRIMMAGE_NAMESPACE
              value: ""
            - name: SCRIMMAGE_DATA_TYPE_PREFIX
              value: ""
            - name: DOMAIN
              value: ""
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"